version: '3'
services:

  # Application
  #---------------------------------------------------------------------------------------------------------------------
  app:
    build: .
    volumes:
    - .:/src/app
    ports:
    - '3001:3001'
    depends_on:
    - postgres
    links:
    - postgres

  # Postgres Database
  # --------------------------------------------------------------------------------------------------------------------
  postgres:
    image: postgres:9.6
    ports:
    - '5430:5432'
    env_file:
      .env
